### ISSUE TITLE
Investment results

### ISSUE THREAD

**Issue by EJohnF** [fartuk/ml_investment#1]
Привет! 
Нашёл этот репозиторий по ссылке из поста на habr. 
Такой вопрос: а вы пробовали делать back-testing инвестирования с результатами ML? Ну т.е. протестировать доходность логики: покупать если недооценена, продавать в обратном случае.

**Comment by fartuk** [comment]
Добрый день! Напрямую сделать бэктест сложно, потому что портфель должен ребалансироваться, например, каждый месяц, и сейчас это делается не полностью автоматически (встречаются явные ошибки, поэтому нельзя брать просто топ по недооцененности). И пока репозиторий позиционируется как инструменты, а не end-to-end стратегии, поэтому написание бэктестов - не приоритетная задача

**Comment by EJohnF** [comment]
Понятно. Будет интересно наблюдать за вашим экспериментом! 
И то что данные предсказания начинаются только с конца ноября 2019 - потому что библиотека не прадоставляет данные за более старые данные? 
Я использовал когда сам пытался модельки строить вот их - https://financialmodelingprep.com/developer/docs/
Они и подешевле чем 30 баксов, и истории данных фин.отчётностей длиннее

**Comment by EJohnF** [comment]
И ещё на счёт групперовки: что если не по секторам их выделать, а на две больших кучи акции роста и акции стоимости? У них разное отношение стоимости компании к её показателям

**Comment by fartuk** [comment]
Предсказания можно было сделать и больше, но я просто взял последние 10 кварталов. По поводу financialmodelingprep.com - сначала купил подписку у них, но было настолько много неверных данных, что пришлось отказаться и перейти на quandl. Про группировки - открытый вопрос, можно да, много чего попробовать, в принципе.
